name: acl-searcher
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blinker=1.9.0
  - click=8.1.7
  - flask=3.0.3
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - libexpat=2.6.4
  - markupsafe=3.0.2
  - pip=24.3.1
  - python=3.12.3
  - python_abi=3.12
  - setuptools=75.6.0
  - werkzeug=3.1.3
  - wheel=0.45.1
