name: acl-searcher
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blinker=1.9.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - click=8.1.7
  - flask=3.0.3
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libnsl=2.0.1
  - libsqlite=3.47.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - python=3.12.3
  - python_abi=3.12
  - readline=8.2
  - setuptools=75.6.0
  - tk=8.6.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xz=5.2.6
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.8
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - bitarray==3.0.0
      - catalogue==2.0.10
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - colbert-ai==0.2.19
      - dataclasses-json==0.6.7
      - datasets==3.1.0
      - deprecated==1.2.15
      - dill==0.3.8
      - dirtyjson==1.0.8
      - distro==1.9.0
      - faiss-cpu==1.9.0.post1
      - fast-pytorch-kmeans==0.2.0.1
      - filelock==3.16.1
      - filetype==1.2.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - git-python==1.0.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.0
      - huggingface-hub==0.26.3
      - idna==3.10
      - jiter==0.8.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.1.20
      - langchain-community==0.0.38
      - langchain-core==0.1.53
      - langchain-text-splitters==0.0.2
      - langsmith==0.1.147
      - llama-cloud==0.1.5
      - llama-index==0.12.2
      - llama-index-agent-openai==0.4.0
      - llama-index-cli==0.4.0
      - llama-index-core==0.12.2
      - llama-index-embeddings-openai==0.3.1
      - llama-index-indices-managed-llama-cloud==0.6.3
      - llama-index-legacy==0.9.48.post4
      - llama-index-llms-openai==0.3.2
      - llama-index-multi-modal-llms-openai==0.3.0
      - llama-index-program-openai==0.3.1
      - llama-index-question-gen-openai==0.3.0
      - llama-index-readers-file==0.4.0
      - llama-index-readers-llama-parse==0.4.0
      - llama-parse==0.5.15
      - marshmallow==3.23.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.2
      - nltk==3.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - onnx==1.17.0
      - openai==1.55.3
      - orjson==3.10.12
      - packaging==23.2
      - pandas==2.2.3
      - pillow==11.0.0
      - propcache==0.2.0
      - protobuf==5.29.0
      - pyarrow==18.1.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pynvml==11.5.3
      - pypdf==5.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - ragatouille==0.0.8.post2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentence-transformers==2.7.0
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.36
      - srsly==2.4.8
      - striprtf==0.0.26
      - sympy==1.13.1
      - tenacity==8.5.0
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tokenizers==0.20.3
      - torch==2.5.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==3.1.0
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - ujson==5.10.0
      - urllib3==2.2.3
      - voyager==2.0.9
      - wrapt==1.17.0
      - xxhash==3.5.0
      - yarl==1.18.0
